---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: pentest-lab

---
# MS SQL Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: pentest-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "YourStrong@Passw0rd"
        - name: MSSQL_PID
          value: "Developer"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
# MS SQL Service
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: pentest-lab
spec:
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
  type: ClusterIP

---
# Vulnerable Web App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: pentest-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: app
        image: python:3.11-slim
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mssql"
        - name: DB_USER
          value: "sa"
        - name: DB_PASSWORD
          value: "YourStrong@Passw0rd"
        - name: DB_NAME
          value: "VulnDB"
        - name: DEBIAN_FRONTEND
          value: "noninteractive"
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e
          echo "Installing dependencies..."
          apt-get update
          apt-get install -y curl gnupg2 ca-certificates
          
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          curl -fsSL https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
          
          apt-get update
          ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
          
          pip install --no-cache-dir flask pyodbc
          
          echo "Creating application..."
          cat > /app.py << 'EOF'
          from flask import Flask, request, jsonify
          import pyodbc
          import time

          app = Flask(__name__)

          def get_connection():
              max_retries = 30
              for i in range(max_retries):
                  try:
                      conn = pyodbc.connect(
                          'DRIVER={ODBC Driver 18 for SQL Server};'
                          'SERVER=mssql;'
                          'DATABASE=VulnDB;'
                          'UID=sa;'
                          'PWD=YourStrong@Passw0rd;'
                          'TrustServerCertificate=yes;'
                      )
                      return conn
                  except Exception as e:
                      print(f"Connection attempt {i+1} failed: {e}")
                      time.sleep(2)
              raise Exception("Could not connect to database")

          def init_db():
              try:
                  # First connect to master to create database
                  conn = pyodbc.connect(
                      'DRIVER={ODBC Driver 18 for SQL Server};'
                      'SERVER=mssql;'
                      'DATABASE=master;'
                      'UID=sa;'
                      'PWD=YourStrong@Passw0rd;'
                      'TrustServerCertificate=yes;'
                  )
                  conn.autocommit = True
                  cursor = conn.cursor()
                  
                  # Create database if it doesn't exist
                  cursor.execute("IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'VulnDB') CREATE DATABASE VulnDB")
                  conn.close()
                  
                  # Now connect to VulnDB
                  conn = get_connection()
                  cursor = conn.cursor()
                  
                  cursor.execute("""
                  IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'users')
                  BEGIN
                      CREATE TABLE users (
                          id INT IDENTITY(1,1) PRIMARY KEY,
                          username NVARCHAR(50),
                          password NVARCHAR(50),
                          email NVARCHAR(100),
                          role NVARCHAR(20)
                      )
                  END
                  """)
                  
                  cursor.execute("SELECT COUNT(*) FROM users")
                  if cursor.fetchone()[0] == 0:
                      cursor.execute("""
                      INSERT INTO users (username, password, email, role) VALUES
                      ('admin', 'admin123', 'admin@example.com', 'admin'),
                      ('john', 'john456', 'john@example.com', 'user'),
                      ('alice', 'alice789', 'alice@example.com', 'user'),
                      ('bob', 'bob321', 'bob@example.com', 'user')
                      """)
                  
                  conn.commit()
                  conn.close()
                  print("Database initialized successfully")
              except Exception as e:
                  print(f"Error initializing database: {e}")

          @app.route('/')
          def home():
              return """
              <h1>MS SQL Injection Pentest Lab</h1>
              <h2>Endpoints:</h2>
              <ul>
                  <li><b>GET /user?id=1</b> - Vulnerable to SQL injection (integer)</li>
                  <li><b>GET /search?q=admin</b> - Vulnerable to SQL injection (string)</li>
                  <li><b>POST /login</b> - Vulnerable login (JSON: {"username":"x","password":"y"})</li>
                  <li><b>GET /users</b> - List all users (safe endpoint)</li>
              </ul>
              <p><b>Database:</b> mssql:1433 | User: sa | Password: YourStrong@Passw0rd</p>
              """

          @app.route('/user')
          def get_user():
              user_id = request.args.get('id', '1')
              # VULNERABLE: Direct string concatenation
              query = f"SELECT * FROM users WHERE id = {user_id}"
              
              try:
                  conn = get_connection()
                  cursor = conn.cursor()
                  cursor.execute(query)
                  rows = cursor.fetchall()
                  conn.close()
                  
                  return jsonify({
                      'query': query,
                      'results': [dict(zip([column[0] for column in cursor.description], row)) for row in rows]
                  })
              except Exception as e:
                  return jsonify({'error': str(e), 'query': query}), 500

          @app.route('/search')
          def search():
              search_term = request.args.get('q', '')
              # VULNERABLE: Direct string concatenation
              query = f"SELECT username, email, role FROM users WHERE username LIKE '%{search_term}%'"
              
              try:
                  conn = get_connection()
                  cursor = conn.cursor()
                  cursor.execute(query)
                  rows = cursor.fetchall()
                  conn.close()
                  
                  return jsonify({
                      'query': query,
                      'results': [dict(zip([column[0] for column in cursor.description], row)) for row in rows]
                  })
              except Exception as e:
                  return jsonify({'error': str(e), 'query': query}), 500

          @app.route('/login', methods=['POST'])
          def login():
              data = request.get_json()
              username = data.get('username', '')
              password = data.get('password', '')
              
              # VULNERABLE: Direct string concatenation
              query = f"SELECT * FROM users WHERE username = '{username}' AND password = '{password}'"
              
              try:
                  conn = get_connection()
                  cursor = conn.cursor()
                  cursor.execute(query)
                  row = cursor.fetchone()
                  conn.close()
                  
                  if row:
                      return jsonify({
                          'success': True,
                          'message': 'Login successful',
                          'query': query,
                          'user': dict(zip([column[0] for column in cursor.description], row))
                      })
                  else:
                      return jsonify({
                          'success': False,
                          'message': 'Invalid credentials',
                          'query': query
                      })
              except Exception as e:
                  return jsonify({'error': str(e), 'query': query}), 500

          @app.route('/users')
          def list_users():
              try:
                  conn = get_connection()
                  cursor = conn.cursor()
                  cursor.execute("SELECT id, username, email, role FROM users")
                  rows = cursor.fetchall()
                  conn.close()
                  
                  return jsonify({
                      'users': [dict(zip([column[0] for column in cursor.description], row)) for row in rows]
                  })
              except Exception as e:
                  return jsonify({'error': str(e)}), 500

          if __name__ == '__main__':
              print("Waiting for database...")
              time.sleep(10)
              init_db()
              print("Starting Flask server on port 5000...")
              app.run(host='0.0.0.0', port=5000, debug=True)
          EOF
          
          echo "Starting application..."
          python /app.py

---
# Vulnerable App Service
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app
  namespace: pentest-lab
spec:
  selector:
    app: vulnerable-app
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
